server:
  port: 8082
  servlet:
    context-path: /api
spring:
  application:
    name: BankTransaction
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123
  cassandra:
    local-datacenter: datacenter1
    keyspace-name: spring_cassandra
    username: cassandra
    password: cassandra
    contact-points: 127.0.0.1
    port: 9042
    schema-action: create_if_not_exists
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      jdbc:
        timezone: UTC
    show-sql: true
  jackson:
    parser:
      allow-numeric-leading-zeros: true
  cloud:
    openfeign:
      client:
        config:
          currency-pair:
            url: ${url-server-currency-pair}
            connect-timeout: 5000
            read-timeout: 5000
          currencies:
            url: ${url-server-currencies}
            connect-timeout: 5000
            read-timeout: 1000
logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: debug
        data:
          cassandra:
            core:
              cql:
                CqlTemplate: DEBUG
        orm:
          jpa: debug


url-server-currency-pair: https://api.twelvedata.com/eod
secret-key: 51c36d7f04f5406c9faa641587be7a20
url-server-currencies: https://api.twelvedata.com/forex_pairs?currency_quote=USD
resilience4j:
  retry:
    instances:
      currency-pair-retry:
        max-attempts: 2
        wait-duration: 1s
  circuitbreaker:
    instances:
      currency-pair-breaker:
        sliding-window-type: count_based
        sliding-window-size: 5
        failure-rate-threshold: 75
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 10s
        max-wait-duration-in-half-open-state: 5s
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 2
