server:
  port: 8081
  servlet:
    context-path: /api
spring:
  application:
    name: ClientTransaction
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      jdbc:
        timezone: UTC
    show-sql: true
  jackson:
    parser:
      allow-numeric-leading-zeros: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/main-changelog-postgres.xml
logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: debug
        data:
          cassandra:
            core:
              cql:
                CqlTemplate: DEBUG
          transaction: debug
        orm:
          jpa: debug
      hibernate.sql: debug
